### ISSUE TITLE
using version and  SRI:hash together fails 

### ISSUE THREAD

**Issue by polearnik** [Elhebert/laravel-sri#11]
webpack.mix.js
```
mix.version([
    "public/css/all.css",
]);
```
main.blade.php
```
<link 
    href="{{ mix("/css/all.css") }}"
    integrity="{{ Sri::hash("/css/all.css") }}" 
    rel="stylesheet"
>
```

in browser console show "None of the "sha256" hashes in the integrity attribute corresponds to the content of the subresource."

**Comment by Elhebert** [comment]
Hi,

It does make sense. When using version, the name of the file created by mix isn't `/css/all.css` but something like `/css/all<hash>.css`.

In this case you should be able to use the `mix()` helper to output the correct file path.

```html
<link 
    href="{{ mix("/css/all.css") }}"
    integrity="{{ Sri::hash(mix("/css/all.css")) }}" 
    rel="stylesheet"
>
```

I have not tried this behaviour, so I have no idea on how it'll react. But I'll look into it 👌

**Comment by polearnik** [comment]
I tried this variant toobut it fails: 
file_get_contents(/home/pol/www/laravel-site/public//css/all.css?id=10e8bca81c7f77c3903c): failed to open stream: No such file or directory

**Comment by Elhebert** [comment]
I see the issue.

You should be able to use `version()` and this package without issue. The problem is simple:

When I'm getting the file, I'm not checking if it's already starting with a `/` before adding one.

I'll accept a PR if you feel up to it.

**Comment by polearnik** [comment]
I think the problem is in "?id=10e8bca81c7f77c3903c".  On getting file  it need remove all after symbol "?".  for example using [ parse_url](http://php.net/manual/ru/function.parse-url.php) 
```
parse_url("/css/all.css?id=10e8bca81c7f77c3903c",PHP_URL_PATH)
```

**Comment by Elhebert** [comment]
Indeed that is also an issue.

But careful on how to fix this, because remote resource could NEED some query parameters to get the correct file.

I would parse the url only when it's a local file.

**Comment by Elhebert** [comment]
I just pushed a fix. It should be alright now.
