### ISSUE TITLE
add example of use @mixSri  and @assetSri

### ISSUE THREAD

**Issue by polearnik** [Elhebert/laravel-sri#16]
I try to use @mixSri as 
```php
@mixSri('/build/css/all.css')
```
and it get me error Undefined index: /'/build/css/all.css'
after  debugging  it work in this case
```php
@mixSri(/build/css/all.css)
```
please add example of use to documentation

**Comment by owenvoke** [comment]
Yeah, I was expecting it to work with quotes as well. I guess this is because Blade directives usually return the PHP as a string (which is then output in the Blade cache files, rather than the calculated output).

**Comment by FrancaR** [comment]
It's will be resolved in PR #30. 🙂
