### ISSUE TITLE
(Suggestion) Sri::html optional parameter

### ISSUE THREAD

**Issue by meduzen** [Elhebert/laravel-sri#2]
Following the [WHATWG spec](https://html.spec.whatwg.org/multipage/urls-and-fetching.html#cors-settings-attributes), the `crossorigin` attribute default value, when the attribute is not omitted, is `anonymous`. This means that the following three declaration are the same:
- `crossorigin=""`
- `crossorigin="anonymous"`
- `crossorigin="i-duno-what-iam-typing"`

So, this could lead to adding a $with_credentials optional parameter to `Sri::html()`, like this:
- `Sri::html('js/app.js')` stays the same and add `crossorigin="anonymous"` (or `crossorigin=""` if we want to save some bits for the browser);
- `Sri::html('js/app.js', false)` will do the same as previous line;
- `Sri::html('js/app.js', true)` will add `crossorigin="use-credentials"`, and could have an alias (`Sri::withCredentials('js/app.js')`).

What do you think?

**Comment by Elhebert** [comment]
Looks good to me.

One could argue that you can use the `hash` method and add the `crossorigin` attribute yourself if you need to customize it.

But I see the added value of an optional flag, like you said, something in the line of 
```
html(string $path, boolean $credentials = false)
```

It's a good first issue for someone new to Open Source !

**Comment by Elhebert** [comment]
I'm currently working on adding Blade directives to the package and I implemented this (in a different way). You can check it here: 
[https://github.com/Elhebert/laravel-sri/blob/feat/blade-directive/src/Sri.php#L17-L26
](https://github.com/Elhebert/laravel-sri/blob/feat/blade-directive/src/Sri.php#L17-L26
)
What do you think?

**Comment by meduzen** [comment]
I find your proposal weaker (but it’s still a step forwards) because the second parameter for `crossorigin` doesn’t enforce a correct value in case of a typo:
- `Sri::html('path/to/file.ext', 'blabliblou')`
- `Sri::html('path/to/file.ext', 'usecredentials')`
- `Sri::html('path/to/file.ext')`

These three examples will all lead to a value interpreted by the browser as `crossorigin="anonymous"`. So it means the user have to keep in mind that the credentials needs a **hyphen**: `Sri::html('path/to/file.ext', 'use-credentials')`. That’s why I originally suggested an alias (`Sri::withCredentials`), which I find easier to remember that _hyphen or not_.

I think it’s easier with a boolean: no parameter or `false` = no credentials. And it also better match the Blade directives (which are very cool 👍) other parameters that are both booleans.

As long as the spec. only allow 2 values for the `crossorigin` parameter, I’d stick to a boolean.

Of course, that’s all personal choice. :)

**Comment by Elhebert** [comment]
I'm still working on removing the booleans, I'm not a fan of having to do something like 
```php 
@sriCss('app/css', false, false, true)
``` 

How are the credentials supposed to be passed when using `use-credentials`? Couldn't find anything about it 🤔

**Comment by meduzen** [comment]
You mean, passed from the browser to the external resource (like in a HTTP header when the resource is fetched)?

**Comment by Elhebert** [comment]
Well, with `use-credentials` the browser is supposed to pass credentials with the request, but where does it take the credentials from? 🤔

**Comment by meduzen** [comment]
I guess a start of answer is in the [MDN doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials):

> The Access-Control-Allow-Credentials response header indicates whether or not the response to the request can be exposed to the page. It can be exposed when the true value is returned.
> Credentials are cookies, authorization headers or TLS client certificates.

Maybe it’s similar to what service-workers requires when they fetch a page (in order to cach it) [with user credentials](https://stackoverflow.com/questions/40666079/service-worker-login-page/40833746#40833746) (cookies at least).
