### ISSUE TITLE
Laravel 5.8 Issue

### ISSUE THREAD

**Issue by HDVinnie** [Elhebert/laravel-sri#23]
When trying to update my application to Laravel 5.8 I am produced with a error that is coming from this package. 

`Class blade.compiler does not exist {"exception":"[object] (ReflectionException(code: -1): Class blade.compiler does not exist at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:794)`

```
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(794): ReflectionClass->__construct('blade.compiler') #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\\Container\\Container->build('blade.compiler') #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\\Container\\Container->resolve('blade.compiler', Array) #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\\Container\\Container->make('blade.compiler', Array) #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1233): Illuminate\\Foundation\\Application->make('blade.compiler') #5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(175): Illuminate\\Container\\Container->offsetGet('blade.compiler') #6 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(144): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance('blade.compiler') #7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(231): Illuminate\\Support\\Facades\\Facade::getFacadeRoot() #8 /var/www/html/vendor/elhebert/laravel-sri/src/SriServiceProvider.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic('directive', Array) #9 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(597): Elhebert\\SubresourceIntegrity\\SriServiceProvider->register() #10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(75): Illuminate\\Foundation\\Application->register(Object(Elhebert\\SubresourceIntegrity\\SriServiceProvider)) #11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(574): Illuminate\\Foundation\\ProviderRepository->load(Array) #12 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders() #13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(210): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap(Object(Illuminate\\Foundation\\Application)) #14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(311): Illuminate\\Foundation\\Application->bootstrapWith(Array) #15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(120): Illuminate\\Foundation\\Console\\Kernel->bootstrap() #16 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput)) #17 {main}
```

https://github.com/laravel/framework/issues/27741

**Comment by HDVinnie** [comment]
Anyone else experiencing this?

**Comment by Elhebert** [comment]
I'll check it out

**Comment by owenvoke** [comment]
This might be related to laravel/framework#25497 🤔

**Comment by owenvoke** [comment]
I managed to resolve this locally by moving the Blade directives to the `::boot()` method. ~Not sure if this is a proper solution though.~ Looks like this is where Blade directives should be registered. 🤔

https://github.com/Elhebert/laravel-sri/blob/541376f578dd8e75d705c0f44357bc1be8ffd620/src/SriServiceProvider.php#L23-L57

According to the documentation:
>You should never attempt to register any event listeners, routes, or any other piece of functionality within the register method. Otherwise, you may accidentally use a service that is provided by a service provider which has not loaded yet.

I wonder if the Blade class binding is getting loaded later on now or something. 🤔

**Comment by owenvoke** [comment]
@HDVinnie, would you be able to test that fix on yours?

I'd also quite like to test it on older versions of Laravel before opening a PR if it works.

**Comment by HDVinnie** [comment]
I sure can test it on laravel 5.7 and 5.8. Ill report back.

**Comment by HDVinnie** [comment]
@Elhebert @pxgamer 

I was able to test this on my two dev servers. One using my projects master branch which is at 5.7 and the other using my shift-5.8 branch.

5.8 branch is fixed when moving Blade directives into boot. 
5.7 master branch doesnt break when adding Blade directives into boot.

Cant test any versions lower then that sorry.

**Comment by owenvoke** [comment]
Cheers. I'll test it on 5.5 and 5.6 later today. :+1:

Edit: Tested, and this seems to work correctly on 5.5 and 5.6 of Laravel.

**Comment by Elhebert** [comment]
Thanks for the investigation guys!

I wasn't able to do this myself at the moment, so big thanks!
