### ISSUE TITLE
Typo in installation instructions

### ISSUE THREAD

**Issue by emzet** [Elhebert/laravel-sri#31]
When I run command `composer require elhebert/laravel-sri@^1.5.2` get this error:

```
[InvalidArgumentException]
  Could not find a matching version of package elhebert/laravel-sri@1.5.2. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).
```

It should be:

`composer require elhebert/laravel-sri ^1.5.2` or `composer require elhebert/laravel-sri:^1.5.2`

then package installs correctly.

**Comment by Elhebert** [comment]
fixed in https://github.com/Elhebert/laravel-sri/commit/df7af56ba23aacb518b5cbc0289db4acf494cd06

Thanks for reporting this!
