### ISSUE TITLE
Hash is not updated when using with Browsersync

### ISSUE THREAD

**Issue by juliomotol** [Elhebert/laravel-sri#48]
Hi, I'm using the `@mixSri('path/to/file.js')` directive and have `mix.browsersync(3000)` in my webpack config. Every time a change had been made and is hot reloaded, the hashes fails. Reloading the page sometime doesn't work. There are times that I need to `php artisan view:clear` then reload in order for it to work. 

I'd suggest to have a config to enable or disable adding hash like you have in laravel-mix-sri doing `mix.generateIntegrityHash({enabled: false})`

UPDATE:
I did a workaround for this for the mean time. I created a `public/mix-sri.json` file and placed blank as their hash.

![image](https://user-images.githubusercontent.com/21353103/76492023-1df30c00-646a-11ea-9c95-54b8dd810097.png)

I hope this gets fixed soon

**Comment by Elhebert** [comment]
This is not the `laravel-mix-sri` repo. 

Please create your issue in the correct repository.

**Comment by juliomotol** [comment]
@Elhebert I'm sorry but you missed my point, The problem is with the `@mixSri` directive generating an integrity hash. This is causing incompatibility with browsersync. It would be nice if we could disable generating a hash when in a development environment.

**Comment by Elhebert** [comment]
Then I don't really understand what the issue is. The regeneration of a hash is the expected behavior. if you don't have any hash specified (either in the config file or in a json file).

I guess we could add a config parameter to enable the hash generation 🤔 But not sure on how useful that would be as SRI is not a feature you should use locally.

**Comment by juliomotol** [comment]
> But not sure on how useful that would be as SRI is not a feature you should use locally.

Yes! That's exactly my problem. I think I didn't explain it well enough, that's on me.

Lets try this again. In my local environment, I'm using Browsersync with Laravel Mix and when every time a `.scss` file is changed, Browsersync injects the updated stylesheet to the currently opened page. But when every time it does that, for some reason the browser rechecks the hash of the file (which is now changed since Browsersync compiled a new stylesheet) and everything falls apart. Reloading the page doesn't work and I always end up running `php artisan view:clear` every time Browsersync compiles a file.

I'm also using your Laravel-mix-sri plugin for this but that has an option that disables the generation of a `mix-sri.json` file when running `npm run dev` or `npm run watch`. So that's out of the question.

### Steps To Reproduce

1. Fresh Install of Laravel.
2. Added packages (Laravel Sri, Laravel Mix Sri, Brow).
3. In `webpack.config.js` add necessary configurations.
     - `.browsersync('3000')` (we are porting browsersync to localhost:3000).
     - `.generateIntegrityHash()` (Optional).
4. Run `php artisan serve` and `npm run watch`.
5. Modify a any `.scss` file.
6. Everything falls apart.

> Note: you may need Laravel UI for the front end scaffolding since they removed it in the earlier versions.

Some Additional details of it could help:
- PHP 7.3.12
- Laravel 7.0.8
- Laravel Sri 2.1.1
- Laravel Mix 5.0.1
- Laravel Mix Sri 0.0.4

I hope I explained it well this time.

**Comment by Elhebert** [comment]
I'll accept a PR that adds a new `enabled` key to the config file that defaults to `false` when not in production. When hashing the file, we should first check if it's enabled or not. If it isn't, we don't add the SRI related attributes.

This behavior should work for both the blade component, but also for people that don't use them.

**Comment by Elhebert** [comment]
Solved in 2.2.0.
