### ISSUE TITLE
@mixSri not reading ASSET_URL set in env

### ISSUE THREAD

**Issue by juliomotol** [Elhebert/laravel-sri#49]
Hi again,

#### Our setup

We are serving our asset via CDN. In my `env` I've set the `ASSET_URL` to our CDN

    ASSET_URL=https://cdnToken.cloudfront.net/

We also have `mix.version()` enabled in our webpack config. 

#### The Problem

When using `@mixSri('js/main.js')`, it only outputs `/js/main.js?id=versionToken` as its `src`.

I tried using `@assetSri(mix('js/main.js'))` but it throws an invalid file exception since by using mix, the file no longer ends with `.js`

https://github.com/Elhebert/laravel-sri/blob/86ab8996d63815e3c17c63284c1a99e45374d81d/src/SriServiceProvider.php#L68-L74

**Comment by Elhebert** [comment]
Both blade directives are generating a `script` or `style` tag. Depending on which you are using, it'll use either the `asset` or the `mix` helper from Laravel.

`mixSri` is using the `mix` helper.
`mxiAsset` is using the `asset` helper.

`@mixSri('js/main.js')` will generate the equivalent as:
```html
<script src="{{ mix('js/main.js') }}" integrity="..." />
```

---

If I understand correctly what you are trying to achieve here: You are deploying your mix compilated files to a CDN and want to use the CDN version with this package right?

**Comment by juliomotol** [comment]
Exactly. For the meantime, we are doing this:

    <script src="{{ asset(mix('js/main.js')) }}" integrity="{{ Sri::hash('js/main.js') }}" ></script>

It would be cleaner if the `@mixSri` supports `asset()` as well.

**Comment by Elhebert** [comment]
From what I can tell, you are miss-using the `asset()` and `mix()` function.
You should never combine both `asset` and `mix` helper as they are both doing different things.

If you look at the Laravel documentation for asset compilation (https://laravel.com/docs/7.x/mix#versioning-and-cache-busting) you will find the following:

> ### Custom Mix Base URLs
> 
> If your Mix compiled assets are deployed to a CDN separate from your application, you will need to change the base URL generated by the `mix` function. You may do so by adding a `mix_url` configuration option to your `config/app.php` configuration file:
> 
> ```php
> 'mix_url' => env('MIX_ASSET_URL', null)
> ```

**Comment by juliomotol** [comment]
Oof. Got this, will use this instead. thanks!
