### ISSUE TITLE
Support for php 8 in 2.* branch

### ISSUE THREAD

**Issue by thirsch** [Elhebert/laravel-sri#71]
As laravel 6 is now compatible to php 8 and also it's currently the LTS version, maybe you should also provide php 8 support in your 2.* branch?

**Comment by Elhebert** [comment]
This isn't my priority at the moment, but I'll accept a PR 👌

**Comment by Elhebert** [comment]
v2.5.0 was just released.

**Comment by thirsch** [comment]
Thanks @Elhebert
