### ISSUE TITLE
Blade component tag name

### ISSUE THREAD

**Issue by thirsch** [Elhebert/laravel-sri#79]
I've upgraded to 3.0 today and wasn't able to use the Blade component tag as described. Am I doing it wrong? The code states `sri.link` and `sri.script`, the documentation `sri-link` and `sri-script`. Is there any magic within the blade system that should convert `.` to `-` and this is not the case in my installation?

**Comment by Elhebert** [comment]
Hello,

Nice catch. The documentation is not matching the implementation. As `sri.link` and `sri.script` are in the code I'll update the documentation instead of the code.
