### ISSUE TITLE
Error when using SRI on Laravel 9.6.0

### ISSUE THREAD

**Issue by Lektarin** [Elhebert/laravel-sri#84]
Hello! I can't use SRI on Laravel 9.6.0, PHP 8.1.4
It writes:
_module "C:/OpenServer/domains/lar.aficionado/node_modules/laravel-mix-sri/build/index"
The module declaration file "laravel-mix-sri" could not be found. "C:/OpenServer/domains/lar.aficionado/node_modules/laravel-mix-sri/build/index .js" has an implicit type of "any".
Try using the command "npm i --save-dev @types/laravel-mix-ru" if it exists, or add a new declaration file (.d.ts) containing "declare module 'laravel-mix-sri';".ts(7016)_
![image](https://user-images.githubusercontent.com/87996224/162200423-519b2179-a4e5-4d49-9efc-cc1c9c4ee89f.png)

**Comment by Elhebert** [comment]
Hello,

Thanks for the issue. however the problem is with the [laravel-mix-sri](https://github.com/Elhebert/laravel-mix-sri) library. Not the Laravel package.
I would suggest to open an issue in that repository.

Thanks.
