### ISSUE TITLE
Sri::hash generates wrong key

### ISSUE THREAD

**Issue by janlew** [Elhebert/laravel-sri#85]
Hello, I'm started using "laravel-sri" with "laravel-mix-sri". It's working without any issues on local environment, but when I push changes on test/live I'm starting getting error messages in console:
**_None of the “sha256” hashes in the integrity attribute match the content of the subresource._**

e.g.
example.js has hash - **_sha256-BxaPYc1tnHx2U8m/aKA8Sx9FEHlg6fvTDsWGCD7NGjA=_** in mix-sri.json
but Chrome requires whole different hash 

**_Failed to find a valid digest in the 'integrity' attribute for resource 'xxx.com/assets/js/example.js?id=3fac7b922ddf2b2605cc177f81e781df' with computed SHA-256 integrity 'eQfO2c01V2pl0xVdxyXFNOjgpWQekJShYmr93w33pwA='. The resource has been blocked._**

It looks like browser calculates different hashes, what should I do to fix this?

**Comment by alexmandrikdev** [comment]
Hello. I have the same problem.

**Comment by Elhebert** [comment]
It seems that this would be a laravel-mix-sri issue rather that this package.
I'm not using these packages anymore, nor supporting them. Especially since Laravel works with Vite now.

Could you share the configuration for both packages? Maybe it's a configuration issue 🤔
