### ISSUE TITLE
Release support for laravel 10

### ISSUE THREAD

**Issue by senyahnoj** [Elhebert/laravel-sri#92]
Hello - please would it be possible to cut a release which is compatible with Laravel 10? 

I am currently using version 3.1.0 which is the latest available from packagist.

Following upgrade guide here from laravel 9 to 10 https://laravel.com/docs/10.x/upgrade and do the composer update, I get a failure message:

```
$ composer update
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires elhebert/laravel-sri ^3.1 -> satisfiable by elhebert/laravel-sri[3.1.0].
    - Conclusion: don't install laravel/framework v10.0.2 (conflict analysis result)
```

Thank you very much!

**Comment by Elhebert** [comment]
Hello,

v3.2.0 was released and should fix this issue 👌

**Comment by senyahnoj** [comment]
Thank you very much!
